apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: hello-nginx
data:
  nginx.conf: |
    user                            nginx;
    worker_processes                auto;
    daemon                          off;

    error_log                       /var/log/nginx/error.log warn;

    events {
        worker_connections          1024;
    }

    http {
        include                     /etc/nginx/mime.types;
        default_type                application/octet-stream;
        sendfile                    on;
        access_log                  /var/log/nginx/access.log;
        keepalive_timeout           3000;
        server {
            listen                  80;
            root                    /www;
            index                   index.html index.htm;
            server_name             localhost;
            client_max_body_size    32m;
            error_page              500 502 503 504  /50x.html;
            location = /50x.html {
                  root              /var/lib/nginx/html;
            }
        }
    }